# Generated by Django 4.0.5 on 2022-06-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
    ]
